### PR TITLE
Allow non-compliant names in the ffms2-sys crate

### PR DESCRIPTION
**Pull request by Christopher22**

### CODE REVIEW

**Comment by Luni-4** [comment]
Could you please use a more descriptive name for the commit? Like the one used for the PR title, thanks! :)

**Comment by Luni-4** [comment]
@Christopher22 

Could you please rebase this one?

**Comment by Christopher22** [comment]
Well, to be honest I thing I lost myself in Git. And that for just one line of change...

**Comment by Luni-4** [comment]
Oh, don't worry! :)

Run `git reset --hard HEAD~5` to return to the `Prepare CI` commit, then run `git commit --amend` to change the commit title, finally pull on your local master branch the upstream changes and in your `clippy` branch run `git rebase master`

It should work, let me know if there are some other problems

**Comment by Christopher22** [comment]
Thank you so much for the "tutorial". I hope, that is now rebased...

**Comment by Luni-4** [comment]
> Thank you so much for the "tutorial". I hope, that is now rebased...

Unfortunately no, this the list of commit  you have right now in your PR: https://github.com/rust-av/ffms2-rs/pull/17/commits

You have to remove nearly all of them (except the first one) locally. To do so, you have to run the `git reset --hard HEAD~8` in order to leave only the `Prepare CI` commit left. 

After that, run `git commit --amend` to replace the title of your initial commit with the title of the PR

At the end,  run:
1. `git checkout master` to move your `HEAD` pointer to your `master` branch
2. `git pull upstream master` to pull the changes of the `master` branch of this repo. I called it `upstream` but you can call it as you want. So, if you don't have the `upstream` label, add it in this way

   - 2.1. `git remote add upstream https://github.com/rust-av/ffms2-rs.git` or if you use SSH `git remote add upstream git@github.com:rust-av/ffms2-rs.git`

3. `git checkout clippy` to move to your clippy branch
4. `git rebase master` to [rebase](https://git-scm.com/book/it/v2/Git-Branching-Rebasing) your `clippy` branch on top of `master`

Some steps could be reduced, but I preferred being clear

**Comment by Christopher22** [comment]
Even more detailed, thank you! At least, the number of commits was now reduced...

**Comment by Luni-4** [comment]
Yes, but I can't see your changes anymore now. Please remove every commit in this PR, add your changes and force push your branch. It should work then

**Comment by Luni-4** [comment]
@Christopher22 

Looking at your PR more carefully, I was able to find your changes. I merged them in the `master` branch, thanks again for your help! :)

We can now close this one

**Pull request closed without merging**
